SET IDENTITY_INSERT [dbo].[Address] ON
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (45, N'52 Di Loreto Lane, Apt 1', N'5230', N'Omaha', 68124, N'Nebraska            ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (46, N'5 Pankratz Parkway, Apt 1', N'10', N'Erie', 70401, N'PA  ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (47, N'5147 Bashford Way', N'90514', N'Mansfield', 70401, N'OH             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (48, N'982 Dorton Circle', N'9', N'Charleston', 20000, N'VA             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (49, N'8 Westerfield Street', N'8', N'Omaha', 70400, N'NB             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (50, N'5 Hallows Lane', N'1365', N'ElPaso', 70403, N'TX             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (51, N'567 XYZ street', N'Street', N'Washington DC', 20005, N'DC             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (52, N'34 Tennessee Parkway', N'2471', N'Watertoen', 02472, N'MA             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (53, N'42472 Magdeline Drive', N'55', N'Toledo', 50000, N'OH             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (54, N'BlueBird Cafe', N'001', N'Nashville', 90031, N'TN             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (55, N'56708 Morningstar Alley', N'1', N'Gary', 80005, N'IN             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (56, N'99401 Nelson Court', N'521', N'Spartanburg', 90001, N'SC             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (57, N'49053 Sutteridge Park', N'815', N'Alexandria', 50000, N'VA             ')
INSERT INTO [dbo].[Address] ([AddressId], [AddressLine1], [AddressLine2], [City], [Zip], [State]) VALUES (58, N'019 La Follette Crossing', N'34', N'Chicago', 60000, N'IL             ')
SET IDENTITY_INSERT [dbo].[Address] OFF
