SET IDENTITY_INSERT [dbo].[Customer] ON
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (71, 1, N'Robenia Frederick                    ', N'customer@domain.com', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (73, 3, N'Eunice Cadman                        ', N'customer21@domain.com', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (74, 4, N'Faina Bodiam                      ', N'customer22@domain.com', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (75, 5, N'Melania Roscamp                    ', N'customer32@domain.com', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (76, 6, N'Fabian Jack                        ', N'customer@42domain.com', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (77, 7, N'Carolus Matlock                    ', N'customer52@domain.com', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (78, 8, N'Fabio Atyea                          ', N'customer62@domain.comr', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (79, 9, N'Alexei Fookes                     ', N'customer72@domain.com', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (80, 10, N'Aldwin Garfield                           ', N'customer82@domain.com', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (81, 11, N'Mignonne Garmanson                        ', N'customer92@domain.com', N'9856875189')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (82, 13, N'Nonie Ondrak                               ', N'customer15@domain.com', N'9856875182')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (83, 23, N'Torrance Domek                       ', N'customer16@domain.com', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (84, 14, N'Robbie Ecclesall                      ', N'customer17@domain.com', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (85, 25, N'Jeremias Hocking                       ', N'customer18@domain.com', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (86, 36, N'Lurleen Korf                           ', N'customer1@domain.com', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (87, 16, N'Vevay Vanns                          ', N'customer1@domain.com', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (88, 27, N'Alysa Pottiphar                       ', N'customer1@domain.com', N'9856875187')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (89, 31, N'Angie Fidoe                      ', N'customer1@domain.com', N'9856875189')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (90, 18, N'Hyacinthe Bransdon                            ', N'customer1@domain.com', N'9856875180')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (91, 29, N'Shawn Pickup                           ', N'Manandhar', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (92, 30, N'Brittani Affron                         ', N'Anish.manandhar@selu.edu', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (93, 39, N'Trish Deschelle                       ', N'Anish.manandhar@selu.edu', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (94, 19, N'Bambie Shieber                           ', N'bl@selu.edu', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (95, 20, N'Dorise Casarino                            ', N'Manandhar', N'9856875181')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (96, 31, N'Dorise Casarino                                  ', N'Anish.manandhar@selu.edu', N'9856875182')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (97, 12, N'Dorise Casarino                                  ', N'bl@selu.edu', N'9856875182')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (98, 23, N'Dorise Casarino                                  ', N'Manandhar', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (99, 34, N'Dorise Casarino                                   ', N'Anish.manandhar@selu.edu', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (100, 15, N'Emelda Hearsum                                  ', N'bl@selu.edu', N'9856875180')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (101, 26, N'Emelda Hearsum                                   ', N'Manandhar', N'9856875189')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (112, 35, N'Emelda Hearsum                              ', N'Anish.manandhar@selu.edu', N'9856875180')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (113, 36, N'Emelda Hearsum                                   ', N'Anish.manandhar@selu.edu', N'9856875181')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (114, 16, N'Emelda Hearsum                                  ', N'bl@selu.edu', N'9856875182')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (115, 25, N'Edee Vero                              ', N'Manandhar', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (116, 37, N'Valma Whitehorne                       ', N'Anish.manandhar@selu.edu', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (117, 18, N'Valma Whitehorne                              ', N'bl@selu.edu', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (118, 29, N'Valma Whitehorne                               ', N'Manandhar', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (119, 37, N'Valma Whitehorne                               ', N'Anish.manandhar@selu.edu', N'9856875187')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (120, 15, N'Adams Tucknutt                               ', N'bl@selu.edu', N'9856875188')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (121, 27, N'Adams Tucknutt                             ', N'Manandhar', N'9856875189')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (122, 39, N'Adams Tucknutt                             ', N'Anish.manandhar@selu.edu', N'9856875180')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (123, 37, N'Neron Lundy                                ', N'Anish.manandhar@selu.edu', N'9856875181')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (124, 15, N'Neron Lundy', N'bl@selu.edu', N'9856875182')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (125, 22, N'Neron Lundy                       ', N'Manandhar', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (126, 31, N'Neron Lundy                        ', N'Anish.manandhar@selu.edu', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (127, 11, N'Neron Lundy                            ', N'bl@selu.edu', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (128, 22, N'Neron Lundy                              ', N'Manandhar', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (129, 38, N'Kliment Michelle                      ', N'Anish.manandhar@selu.edu', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (130, 16, N'Hedy Danett                              ', N'bl@selu.edu', N'9856875187')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (131, 27, N'Hedy Danett                             ', N'Manandhar', N'9856875188')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (132, 34, N'Hedy Danett                                     ', N'Anish.manandhar@selu.edu', N'9856875189')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (133, 37, N'Kerrill Laight                             ', N'Anish.manandhar@selu.edu', N'9856875180')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (134, 15, N'Kerrill Laight                           ', N'bl@selu.edu', N'9856875181')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (135, 26, N'Kerrill Laight                   ', N'Manandhar', N'9856875182')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (136, 39, N'Bryn Gilpillan                          ', N'Anish.manandhar@selu.edu', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (137, 17, N'Lorraine Brosel                            ', N'bl@selu.edu', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (138, 27, N'Lorraine Brosel                                ', N'Manandhar', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (139, 37, N'Cissy Yes                              ', N'Anish.manandhar@selu.edu', N'9856875153')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (140, 10, N'Neille Tabourin                     ', N'bl@selu.edu', N'9856875186')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (141, 20, N'Mike Beatey                            ', N'Manandhar', N'9856875187')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (142, 30, N'Erie D Aulby                      ', N'Anish.manandhar@selu.edu', N'9856875188')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (143, 31, N'Wayland Ghelardoni                              ', N'Anish.manandhar@selu.edu', N'9856875189')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (144, 11, N'Corissa Samson                            ', N'bl@selu.edu', N'9856875180')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (145, 21, N'Corissa Samson                              ', N'Manandhar', N'9856875185')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (146, 32, N'Stanleigh Villar                                ', N'Anish.manandhar@selu.edu', N'9856875184')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (147, 12, N'Stanleigh Villar', N'bl@selu.edu', N'9856875183')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (148, 22, N'Carmine Munkton                                 ', N'Manandhar', N'9856875182')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (149, 33, N'Hanni Goch                                    ', N'Anish.manandhar@selu.edu', N'9856875181')
INSERT INTO [dbo].[Customer] ([CustomerId], [Address], [Name], [Email], [Phone]) VALUES (152, 3, N'Anish                                             ', N'Anish.manandhar@selu.edu', N'9856875180')


SET IDENTITY_INSERT [dbo].[Customer] OFF
